export const mockUser1 = {
    _id: '123',
    name: 'testuser',
    email: 'unit@test.com',
    accountCreatedOn: '2025-07-14T00:00:00Z',
    emailVerificationCode: 'ABC123',
    profilePhoto: null,
    profileInfo: {
        bio: 'Coffee lover. Laxing.',
        favouriteDestination: 'Taiwan, China, USA',
        gender: 'Male',
        dateOfBirth: '2003-01-01T00:00:00Z',
        location: 'Singapore',
    },
    friendsWith: ['456', '789'],
    emailSignUp: true,
};
export const mockUser2 = {
    _id: '456',
    name: 'janedoe',
    email: 'jane.doe@example.com',
    accountCreatedOn: '2025-06-10T00:00:00Z',
    emailVerificationCode: 'XYZ789',
    profilePhoto: null,
    profileInfo: {
        bio: 'World explorer and foodie.',
        favouriteDestination: 'Japan, France, Italy',
        gender: 'Female',
        dateOfBirth: '2000-05-15T00:00:00Z',
        location: 'New York, USA',
    },
    friendsWith: ['123'],
    emailSignUp: true,
};
export const mockUser3 = {
    _id: '789',
    name: 'alexwander',
    email: 'alex@wanderlust.dev',
    accountCreatedOn: '2024-12-01T00:00:00Z',
    emailVerificationCode: 'LMN456',
    profilePhoto: null,
    profileInfo: {
        bio: 'Digital nomad and writer.',
        favouriteDestination: 'Portugal, Peru, South Africa',
        gender: 'Male',
        dateOfBirth: '2005-09-30T00:00:00Z',
        location: 'Lisbon, Portugal',
    },
    friendsWith: ['123', '456'],
    emailSignUp: false,
};

export const mockItinerary = [
    {
        _id: "1",
        user: "testuser",
        collaborators: [],
        tripName: "Test Trip",
        destination: "Singapore",
        imageNumber: 3,
        startDate: "2025-07-13",
        endDate: "2025-07-13",
        numberOfPeople: 1,
        activities: [],
        notes: "mock itinerary",
    },
    {
        _id: "2",
        user: "testuser",
        collaborators: [mockUser2, mockUser3],
        tripName: "Weekend Getaway",
        destination: "Kuala Lumpur",
        imageNumber: 5,
        startDate: "2025-08-01",
        endDate: "2025-08-03",
        numberOfPeople: 2,
        activities: [
            {
                _id: "2a",
                activityName: "Bus Ride",
                date: "2025-08-01",
                startTime: "09:00",
                endTime: "13:00",
                type: "Transport",
                notes: "Express coach from Singapore",
            },
            {
                _id: "2b",
                activityName: "Check-in Hotel",
                date: "2025-08-01",
                startTime: "14:00",
                endTime: "14:30",
                type: "Transport",
                notes: "Hilton KL",
            },
            {
                _id: "2c",
                activityName: "Dinner at Jalan Alor",
                date: "2025-08-02",
                startTime: "19:00",
                endTime: "20:30",
                type: "Meal",
                notes: "Try satay and char kway teow",
            }
        ],
        notes: "Relaxing city trip"
    },
    {
        _id: "3",
        user: "testuser",
        collaborators: [],
        tripName: "Nature Retreat",
        destination: "Bali",
        imageNumber: 8,
        startDate: "2025-09-10",
        endDate: "2025-09-15",
        numberOfPeople: 4,
        activities: [
            {
                _id: "3a",
                activityName: "Flight to Bali",
                date: "2025-09-10",
                startTime: "10:00",
                endTime: "14:00",
                type: "Transport",
                notes: "Flight SQ938",
            },
            {
                _id: "3b",
                activityName: "Ubud Rice Terrace Tour",
                date: "2025-09-11",
                startTime: "09:00",
                endTime: "12:00",
                type: "Sightseeing",
                notes: "Photography session",
            },
            {
                _id: "3c",
                activityName: "Beach Day",
                date: "2025-09-13",
                startTime: "11:00",
                endTime: "17:00",
                type: "Leisure",
                notes: "Seminyak beach",
            }
        ],
        notes: "Escape from city life",
    },
];